# @author: David Lee
# PROJ is the file name of your module.
PROJ = pushbutton_test
RAGOBOTDIR = ../../..

# Set SOSDIR to the SOS directory
ROOTDIR = $(SOSDIR)

include $(RAGOBOTDIR)/modules/mc/Makemod

