
PROJ = blueled_test_app
RAGOBOTDIR = ../../..

SRCS += cb2bus_hardware.c pushbutton.c cb2bus.c hipri_int.c blueled_test.c

include ../../Makerules

vpath cb2bus_hardware.c $(RAGOBOTDIR)/modules/hardware/micax/cb2bus/
vpath pushbutton.c $(RAGOBOTDIR)/modules/hardware/micax/pushbutton/
vpath hipri_int.c $(RAGOBOTDIR)/modules/hardware/micax/hipri_int/
vpath cb2bus.c $(RAGOBOTDIR)/modules/mc/cb2bus/
vpath blueled_test.c $(RAGOBOTDIR)/modules/test/blueled_test/