
PROJ = motorcontrol_test_app
RAGOBOTDIR = ../../..

SRCS += cb2bus_hardware.c hipri_int.c cb2bus.c motorcontrol.c motorcontrol_test.c

include ../../Makerules

vpath cb2bus_hardware.c $(RAGOBOTDIR)/modules/hardware/micax/cb2bus/
vpath hipri_int.c $(RAGOBOTDIR)/modules/hardware/micax/hipri_int/
vpath cb2bus.c $(RAGOBOTDIR)/modules/mc/cb2bus/
vpath motorcontrol.c $(RAGOBOTDIR)/modules/mc/motorcontrol/
vpath motorcontrol_test.c $(RAGOBOTDIR)/modules/test/motorcontrol_test/