
PROJ = inertialsensor_test_app
RAGOBOTDIR = ../../..

SRCS += cb2bus_hardware.c pushbutton.c cb2bus.c inertialsensor.c inertialsensor_test.c

include ../../Makerules

vpath cb2bus_hardware.c $(RAGOBOTDIR)/modules/hardware/micax/cb2bus/
vpath pushbutton.c $(RAGOBOTDIR)/modules/hardware/micax/pushbutton/
vpath cb2bus.c $(RAGOBOTDIR)/modules/mc/cb2bus/
vpath inertialsensor.c $(RAGOBOTDIR)/modules/mc/inertialsensor/
vpath inertialsensor_test.c $(RAGOBOTDIR)/modules/test/inertialsensor_test/