
PROJ = servos_test_app
RAGOBOTDIR = ../../..

SRCS += cb2bus_hardware.c pushbutton.c cb2bus.c servos.c servos_test.c

include ../../Makerules

vpath cb2bus_hardware.c $(RAGOBOTDIR)/modules/hardware/micax/cb2bus/
vpath pushbutton.c $(RAGOBOTDIR)/modules/hardware/micax/pushbutton/
vpath servos.c $(RAGOBOTDIR)/modules/hardware/micax/servos/
vpath cb2bus.c $(RAGOBOTDIR)/modules/mc/cb2bus/
vpath servos_test.c $(RAGOBOTDIR)/modules/test/servos_test/