
PROJ = cb2bus_test_app
RAGOBOTDIR = ../../..

SRCS += cb2bus_hardware.c cb2bus.c cb2bus_test.c

include ../../Makerules

vpath cb2bus_hardware.c $(RAGOBOTDIR)/modules/hardware/micax/cb2bus/
vpath cb2bus.c $(RAGOBOTDIR)/modules/mc/cb2bus/
vpath cb2bus_test.c $(RAGOBOTDIR)/modules/test/cb2bus_test/