# @author: David Lee
# PROJ is the file name of your module.
PROJ = hipri_int_test
RAGOBOTDIR = ../../..

# Set SOSDIR to the SOS directory
ROOTDIR = $(SOSDIR)

include $(RAGOBOTDIR)/modules/Makemod

