# @author: David Lee
# PROJ is the file name of your module.
PROJ = battery_monitor
RAGOBOTDIR = ../../..

# Set SOSDIR to the SOS directory
ROOTDIR = $(SOSDIR)

include $(RAGOBOTDIR)/modules/Makemod

