
PROJ = lightshow_test_app
RAGOBOTDIR = ../../..

SRCS += cb2bus_hardware.c pushbutton.c cb2bus.c lightshow.c lightshow_test.c

include ../../Makerules

vpath cb2bus_hardware.c $(RAGOBOTDIR)/modules/hardware/micax/cb2bus/
vpath pushbutton.c $(RAGOBOTDIR)/modules/hardware/micax/pushbutton/
vpath cb2bus.c $(RAGOBOTDIR)/modules/mc/cb2bus/
vpath lightshow.c $(RAGOBOTDIR)/modules/mc/lightshow/
vpath lightshow_test.c $(RAGOBOTDIR)/modules/test/lightshow_test/