# @author: Ilias Tsigkogiannis
# PROJ is the file name of your module.
PROJ = magsensor_test
RAGOBOTDIR = ../../..

# Set SOSDIR to the SOS directory
ROOTDIR = $(SOSDIR)

include $(RAGOBOTDIR)/modules/mc/Makemod

