
PROJ = irranger_test_app
RAGOBOTDIR = ../../..

SRCS += cb2bus_hardware.c irranger.c cb2bus.c pushbutton.c irranger_test.c

include ../../Makerules

vpath cb2bus_hardware.c $(RAGOBOTDIR)/modules/hardware/micax/cb2bus/
vpath pushbutton.c $(RAGOBOTDIR)/modules/hardware/micax/pushbutton/
vpath irranger.c $(RAGOBOTDIR)/modules/hardware/micax/irranger/
vpath cb2bus.c $(RAGOBOTDIR)/modules/mc/cb2bus/
vpath irranger_test.c $(RAGOBOTDIR)/modules/test/irranger_test/