/* -*- Mode: C; tab-width:4 -*- */
/* ex: set ts=4 shiftwidth=4 softtabstop=4 cindent: */
/*                                  tab:4
 * "Copyright (c) 2000-2003 The Regents of the University  of California.  
 * All rights reserved.
 *
 * Permission to use, copy, modify, and distribute this software and its
 * documentation for any purpose, without fee, and without written agreement is
 * hereby granted, provided that the above copyright notice, the following
 * two paragraphs and the author appear in all copies of this software.
 * 
 * IN NO EVENT SHALL THE UNIVERSITY OF CALIFORNIA BE LIABLE TO ANY PARTY FOR
 * DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES ARISING OUT
 * OF THE USE OF THIS SOFTWARE AND ITS DOCUMENTATION, EVEN IF THE UNIVERSITY OF
 * CALIFORNIA HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 * 
 * THE UNIVERSITY OF CALIFORNIA SPECIFICALLY DISCLAIMS ANY WARRANTIES,
 * INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS FOR A PARTICULAR PURPOSE.  THE SOFTWARE PROVIDED HEREUNDER IS
 * ON AN "AS IS" BASIS, AND THE UNIVERSITY OF CALIFORNIA HAS NO OBLIGATION TO
 * PROVIDE MAINTENANCE, SUPPORT, UPDATES, ENHANCEMENTS, OR MODIFICATIONS."
 *
 *
 */
/**
 * @author David Lee
 */
/**
 * @brief Provides support for the hipri_int interrupt 
 *
 * A hipri_int interrupt is generated by IRMAN or another attached processor
 * on the Nerve board when either wants to alert the Brain board of an 
 * important event.
 */

#include "mica2_peripheral.h"

#define MAXREGMOD  2  //the maximum number of modules that can register
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// LOCAL VARIABLES
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

static uint8_t registered_modules[MAXREGMOD];
static uint8_t numRegMod; //the number of registered modules
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
// LOCAL FUNCTIONS
//++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
static void hipri_int_broadcast(uint8_t cause);

void hipri_int_init()
{
  //Set PE7, the hipri_int, to an input pin
  cbi(DDRE, 7);
  cbi(PORTE, 7);

  //enable INT6
  sbi(EIMSK, 7);

  //generate interrupt on rising edge
  sbi(EICRB, 7);
  sbi(EICRB, 6);

  //Set PG2, the irman_hi signal to an input pin. 
  cbi(DDRG, 2);
  cbi(PORTG, 2);

  //Set PC0, the irman_reset signal to input. 
  cbi(DDRC, 0);
  cbi(PORTC, 0);
} 

void hipri_int_broadcast(uint8_t cause)
{
  uint8_t i;
  for (i = 0; i < numRegMod; i++) 
	{
	  post_short(registered_modules[i], registered_modules[i], MSG_HIPRI_INT, cause, 0, SOS_MSG_HIGH_PRIORITY);
	}
}

//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
//HIPRI_INT INTERRUPT
//+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
SIGNAL(SIG_INTERRUPT7) 
{
  HAS_CRITICAL_SECTION;
  ENTER_CRITICAL_SECTION();
  //if IRMAN_HI is 1, then broadcast to all registered modules that IRMAN
  //created the interrupt; otherwise, the processor on the Nerve board
  //created the interrupt. IRMAN always has precendence over the Nerve board
  if ((PING & 0x02) != 0) 
	{
	  hipri_int_broadcast(IRMAN_INTERRUPT);
	}
  else
	{
	  hipri_int_broadcast(PROC_INTERRUPT);
	}
  LEAVE_CRITICAL_SECTION();
} 

int8_t ker_hipri_int_register(uint8_t pid)
{
  if (numRegMod == MAXREGMOD) 
	{
	  return -EINVAL;
	}
  registered_modules[numRegMod] = pid;
  numRegMod += 1;
  return SOS_OK;
}
int8_t ker_hipri_int_deregister(uint8_t pid)
{
  uint8_t i;
  if (numRegMod == 0) 
	{
	  return -EINVAL;
	}
  // Find the pid in the table. If it is found, remove the pid, shrink the 
  // table and return SOS_OK. If not found, return -EINVAL
  for (i = 0; i < numRegMod; i++) 
	{
	  if (registered_modules[i] == pid) 
		{
		  for (i=i+1; i < numRegMod; i++) 
			{
			  registered_modules[i-1] = registered_modules[i];
			}
		  numRegMod--;
		  return SOS_OK;
		}  
	}
  return -EINVAL;
}
