/**
 * This class is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This class implements a Java interface to the 'CommandMsg'
 * message type.
 */

public class CommandMsg extends net.tinyos.message.Message {

    /** The default size of this message type in bytes. */
    public static final int DEFAULT_MESSAGE_SIZE = 29;

    /** The Active Message type associated with this message. */
    public static final int AM_TYPE = 11;

    /** Create a new CommandMsg of size 29. */
    public CommandMsg() {
        super(DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /** Create a new CommandMsg of the given data_length. */
    public CommandMsg(int data_length) {
        super(data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CommandMsg with the given data_length
     * and base offset.
     */
    public CommandMsg(int data_length, int base_offset) {
        super(data_length, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CommandMsg using the given byte array
     * as backing store.
     */
    public CommandMsg(byte[] data) {
        super(data);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CommandMsg using the given byte array
     * as backing store, with the given base offset.
     */
    public CommandMsg(byte[] data, int base_offset) {
        super(data, base_offset);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CommandMsg using the given byte array
     * as backing store, with the given base offset and data length.
     */
    public CommandMsg(byte[] data, int base_offset, int data_length) {
        super(data, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CommandMsg embedded in the given message
     * at the given base offset.
     */
    public CommandMsg(net.tinyos.message.Message msg, int base_offset) {
        super(msg, base_offset, DEFAULT_MESSAGE_SIZE);
        amTypeSet(AM_TYPE);
    }

    /**
     * Create a new CommandMsg embedded in the given message
     * at the given base offset and length.
     */
    public CommandMsg(net.tinyos.message.Message msg, int base_offset, int data_length) {
        super(msg, base_offset, data_length);
        amTypeSet(AM_TYPE);
    }

    /**
    /* Return a String representation of this message. Includes the
     * message type name and the non-indexed field values.
     */
    public String toString() {
      String s = "Message <CommandMsg> \n";
      try {
        s += "  [id=0x"+Long.toHexString(get_id())+"]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [point.x=";
        for (int i = 0; i < 7; i++) {
          s += "0x"+Long.toHexString(getElement_point_x(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      try {
        s += "  [point.y=";
        for (int i = 0; i < 7; i++) {
          s += "0x"+Long.toHexString(getElement_point_y(i) & 0xff)+" ";
        }
        s += "]\n";
      } catch (ArrayIndexOutOfBoundsException aioobe) { /* Skip field */ }
      return s;
    }

    // Message-type-specific access methods appear below.

    /////////////////////////////////////////////////////////
    // Accessor methods for field: id
    //   Field type: short
    //   Offset (bits): 0
    //   Size (bits): 8
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'id' is signed (false).
     */
    public static boolean isSigned_id() {
        return false;
    }

    /**
     * Return whether the field 'id' is an array (false).
     */
    public static boolean isArray_id() {
        return false;
    }

    /**
     * Return the offset (in bytes) of the field 'id'
     */
    public static int offset_id() {
        return (0 / 8);
    }

    /**
     * Return the offset (in bits) of the field 'id'
     */
    public static int offsetBits_id() {
        return 0;
    }

    /**
     * Return the value (as a short) of the field 'id'
     */
    public short get_id() {
        return (short)getUIntElement(offsetBits_id(), 8);
    }

    /**
     * Set the value of the field 'id'
     */
    public void set_id(short value) {
        setUIntElement(offsetBits_id(), 8, value);
    }

    /**
     * Return the size, in bytes, of the field 'id'
     */
    public static int size_id() {
        return (8 / 8);
    }

    /**
     * Return the size, in bits, of the field 'id'
     */
    public static int sizeBits_id() {
        return 8;
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: point.x
    //   Field type: int[]
    //   Offset (bits): 0
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'point.x' is signed (false).
     */
    public static boolean isSigned_point_x() {
        return false;
    }

    /**
     * Return whether the field 'point.x' is an array (true).
     */
    public static boolean isArray_point_x() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'point.x'
     */
    public static int offset_point_x(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 7) throw new ArrayIndexOutOfBoundsException();
        offset += 8 + index1 * 32;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'point.x'
     */
    public static int offsetBits_point_x(int index1) {
        int offset = 0;
        if (index1 < 0 || index1 >= 7) throw new ArrayIndexOutOfBoundsException();
        offset += 8 + index1 * 32;
        return offset;
    }

    /**
     * Return the entire array 'point.x' as a int[]
     */
    public int[] get_point_x() {
        int[] tmp = new int[7];
        for (int index0 = 0; index0 < numElements_point_x(0); index0++) {
            tmp[index0] = getElement_point_x(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'point.x' from the given int[]
     */
    public void set_point_x(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_point_x(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'point.x'
     */
    public int getElement_point_x(int index1) {
        return (int)getUIntElement(offsetBits_point_x(index1), 16);
    }

    /**
     * Set an element of the array 'point.x'
     */
    public void setElement_point_x(int index1, int value) {
        setUIntElement(offsetBits_point_x(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'point.x'
     */
    public static int totalSize_point_x() {
        return (224 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'point.x'
     */
    public static int totalSizeBits_point_x() {
        return 224;
    }

    /**
     * Return the size, in bytes, of each element of the array 'point.x'
     */
    public static int elementSize_point_x() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'point.x'
     */
    public static int elementSizeBits_point_x() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'point.x'
     */
    public static int numDimensions_point_x() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'point.x'
     */
    public static int numElements_point_x() {
        return 7;
    }

    /**
     * Return the number of elements in the array 'point.x'
     * for the given dimension.
     */
    public static int numElements_point_x(int dimension) {
      int array_dims[] = { 7,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

    /////////////////////////////////////////////////////////
    // Accessor methods for field: point.y
    //   Field type: int[]
    //   Offset (bits): 16
    //   Size of each element (bits): 16
    /////////////////////////////////////////////////////////

    /**
     * Return whether the field 'point.y' is signed (false).
     */
    public static boolean isSigned_point_y() {
        return false;
    }

    /**
     * Return whether the field 'point.y' is an array (true).
     */
    public static boolean isArray_point_y() {
        return true;
    }

    /**
     * Return the offset (in bytes) of the field 'point.y'
     */
    public static int offset_point_y(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 7) throw new ArrayIndexOutOfBoundsException();
        offset += 8 + index1 * 32;
        return (offset / 8);
    }

    /**
     * Return the offset (in bits) of the field 'point.y'
     */
    public static int offsetBits_point_y(int index1) {
        int offset = 16;
        if (index1 < 0 || index1 >= 7) throw new ArrayIndexOutOfBoundsException();
        offset += 8 + index1 * 32;
        return offset;
    }

    /**
     * Return the entire array 'point.y' as a int[]
     */
    public int[] get_point_y() {
        int[] tmp = new int[7];
        for (int index0 = 0; index0 < numElements_point_y(0); index0++) {
            tmp[index0] = getElement_point_y(index0);
        }
        return tmp;
    }

    /**
     * Set the contents of the array 'point.y' from the given int[]
     */
    public void set_point_y(int[] value) {
        for (int index0 = 0; index0 < value.length; index0++) {
            setElement_point_y(index0, value[index0]);
        }
    }

    /**
     * Return an element (as a int) of the array 'point.y'
     */
    public int getElement_point_y(int index1) {
        return (int)getUIntElement(offsetBits_point_y(index1), 16);
    }

    /**
     * Set an element of the array 'point.y'
     */
    public void setElement_point_y(int index1, int value) {
        setUIntElement(offsetBits_point_y(index1), 16, value);
    }

    /**
     * Return the total size, in bytes, of the array 'point.y'
     */
    public static int totalSize_point_y() {
        return (224 / 8);
    }

    /**
     * Return the total size, in bits, of the array 'point.y'
     */
    public static int totalSizeBits_point_y() {
        return 224;
    }

    /**
     * Return the size, in bytes, of each element of the array 'point.y'
     */
    public static int elementSize_point_y() {
        return (16 / 8);
    }

    /**
     * Return the size, in bits, of each element of the array 'point.y'
     */
    public static int elementSizeBits_point_y() {
        return 16;
    }

    /**
     * Return the number of dimensions in the array 'point.y'
     */
    public static int numDimensions_point_y() {
        return 1;
    }

    /**
     * Return the number of elements in the array 'point.y'
     */
    public static int numElements_point_y() {
        return 7;
    }

    /**
     * Return the number of elements in the array 'point.y'
     * for the given dimension.
     */
    public static int numElements_point_y(int dimension) {
      int array_dims[] = { 7,  };
        if (dimension < 0 || dimension >= 1) throw new ArrayIndexOutOfBoundsException();
        if (array_dims[dimension] == 0) throw new IllegalArgumentException("Array dimension "+dimension+" has unknown size");
        return array_dims[dimension];
    }

}
