# @author: David Lee
# PROJ is the file name of your module.
PROJ = cb2bus_hardware
RAGOBOTDIR = ../../../..

# Set SOSDIR to the SOS directory
#ROOTDIR = ../../../../../../../../../../sos-1.x
ROOTDIR = $(SOSDIR)
include $(RAGOBOTDIR)/modules/Makemod

